// Mendefinisikan array kata-kata mutiara
const quotes = [
  "Hiduplah seolah-olah kamu akan mati besok, belajarlah seolah-olah kamu akan hidup selamanya. -Mahatma Gandhi",
  "Kesuksesan bukanlah kunci kebahagiaan. Kebahagiaanlah kunci kesuksesan. Jika kamu mencintai apa yang kamu lakukan, kamu akan sukses. -Albert Schweitzer",
  "Berhentilah berbicara dan mulailah bertindak. Berhentilah mengeluh dan mulailah bersyukur. Berhentilah meminta-minta dan mulailah memberi. Berhentilah mengkhawatirkan dirimu sendiri dan mulailah memikirkan orang lain. -Roy T. Bennett",
  "Pada akhirnya, kita hanya menyesali kesempatan yang tidak kita ambil, hubungan yang tidak kita pelihara, dan mimpi yang kita biarkan mati. -Darius Rucker",
  "Hidup ini adalah milikmu. Jadilah orang yang mengendalikan dirimu sendiri, bukan menjadi orang yang dikendalikan oleh hidupmu. -Unknown",
  "Hanya satu hal yang bisa membuat mimpi tidak tercapai, yaitu menyerah sebelum kamu mencapainya. -Toba Beta",
  "Jangan biarkan orang lain merubah caramu berpikir, karena itu akan mengubah cara hidupmu. -Sherry Argov",
  "Jangan pernah mengeluh tentang apa yang tidak kamu miliki. Keluhkanlah tentang apa yang kamu miliki yang tidak kamu hargai. -Unknown",
  "Kebahagiaan tidak bisa didapatkan dengan mengejar-ngejar, tetapi hanya bisa dicapai dengan merangkul apa yang telah ada. -Unknown",
  "Tidak ada orang yang bisa membuatmu merasa tidak berharga tanpa persetujuanmu. -Eleanor Roosevelt",
  "Jangan pernah meremehkan kekuatan kata-kata, karena kata-kata bisa meruntuhkan segalanya atau membangun semuanya. -Unknown",
  "Jangan biarkan kegagalan mempengaruhi cara kamu melihat dirimu sendiri. -Unknown",
  "Semua mimpi besar dimulai dengan mimpi kecil. Jangan pernah meremehkan mimpi kecilmu. -Unknown",
  "Jangan pernah takut untuk gagal. Kesuksesan adalah hasil dari belajar dari kegagalan. -Unknown",
  "Hidupmu adalah cerita yang harus kamu tulis sendiri. Jangan biarkan orang lain menulisnya untukmu. -Unknown",
  "Belajarlah dari kemarin, impikan besok, tetapi yang terpenting adalah lakukan hari ini. -Unknown",
  "Jangan menyerah hanya karena hal itu sulit. Yang sulitlah yang membuatnya berharga. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mengubah dirimu sendiri dan dunia di sekitarmu. -Unknown",
  "Terkadang kebahagiaan bisa ditemukan di tempat-tempat yang paling tidak terduga. -Unknown",
  "Jangan biarkan masa lalu yang tidak bahagia menghancurkan kebahagiaanmu di masa depan. -Unknown",
  "Jangan berhenti mencoba hanya karena kamu mengalami kegagalan. Kegagalan adalah kesempatan untuk mencoba lagi dengan lebih bijak. -Unknown",
  "Jangan biarkan kegagalan hari ini merusak kemungkinan suksesmu besok. -Unknown",
  "Hidup adalah perjalanan yang singkat. Jangan sia-siakan waktumu untuk hal-hal yang tidak berarti. -Unknown",
  "Jangan biarkan ketakutanmu menghalangi impianmu. -Unknown",
  "Jika kamu tidak berani memulai, maka kamu tidak akan pernah sampai di mana kamu ingin pergi. -Unknown",
  "Jangan pernah mengabaikan orang yang mencintaimu, karena mereka yang paling dekat denganmu biasanya adalah orang-orang yang akan selalu ada untukmu. -Unknown",
  "Kepercayaan pada dirimu adalah kunci untuk mencapai kesuksesan. -Unknown",
  "Jangan pernah meremehkan kekuatan kata-katamu. Kata-kata yang baik bisa merubah dunia. -Unknown",
  "Kamu adalah satu-satunya orang yang bisa membuat keputusan untuk hidupmu. -Unknown",
  "Jangan pernah mengubah dirimu sendiri hanya agar bisa disukai oleh orang lain. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mengubah dunia, karena itu adalah kekuatanmu untuk mengubah duniamu sendiri. -Unknown",
  "Jangan pernah takut untuk mengambil risiko, karena itu adalah risiko yang membuat hidup kita menjadi berarti. -Unknown",
  "Jangan biarkan masa lalu merusak hari ini dan masa depanmu. -Unknown",
  "Hidup ini adalah tentang menciptakan dirimu sendiri. -George Bernard Shaw",
  "Ketika kamu mempercayai dirimu sendiri, kamu akan tahu bagaimana cara hidup. -Johann Wolfgang von Goethe",
  "Mimpi besar berasal dari mimpi kecil yang digariskan dengan detail. -Unknown",
  "Jangan pernah menyerah pada impianmu. Impianmu adalah bagian dari dirimu yang paling asli dan otentik. -Unknown",
  "Kegagalan adalah pilihan untuk memulai lagi dengan lebih cerdas. -Henry Ford",
  "Keberhasilan tidak datang kepada mereka yang menunggu, tetapi kepada mereka yang bertindak. -Unknown",
  "Jangan pernah berhenti mencoba, karena kamu tidak pernah tahu kapan kamu akan sukses. -Unknown",
  "Orang yang paling bahagia bukanlah yang memiliki segalanya, tetapi mereka yang tahu bagaimana cara mensyukuri apa yang mereka miliki. -Unknown",
  "Setiap kegagalan adalah kesempatan untuk memulai lagi dengan lebih baik. -Unknown",
  "Kamu tidak perlu menjadi sempurna untuk menjadi bahagia. Kamu hanya perlu belajar mencintai dirimu sendiri sebagai bagian dari proses menuju kesempurnaan. -Unknown",
  "Jangan pernah takut untuk melakukan hal-hal yang baru, karena itu adalah langkah pertama menuju kemajuan. -Unknown",
  "Jangan biarkan kegagalan menjadi alasan untuk menyerah. Kegagalan adalah kesempatan untuk mencoba lagi dengan lebih baik. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mempengaruhi orang lain. Kamu mungkin tidak menyadarinya, tetapi setiap tindakanmu memiliki dampak pada orang di sekitarmu. -Unknown",
  "Ketika kamu melakukan hal yang kamu cintai, kamu tidak akan pernah merasa seperti kamu bekerja. -Unknown",
  "Jangan pernah mengorbankan nilai-nilai pentingmu hanya untuk meraih kesuksesan sementara. -Unknown",
  "Hidup adalah tentang menciptakan nilai bagi orang lain. -Unknown",
  "Jangan menyerah hanya karena kamu merasa sulit. Jangan lupa, kamu memiliki kekuatan untuk mengatasi semua rintangan. -Unknown",
  "Setiap hari adalah kesempatan baru untuk menjadi lebih baik dari sebelumnya. -Unknown",
  "Jangan pernah meremehkan kekuatan doa. Doa adalah kunci untuk meraih kesuksesan sejati. -Unknown",
  "Jangan biarkan dirimu terjebak dalam rutinitas yang membosankan. Lakukan sesuatu yang baru setiap hari dan nikmati keindahan hidup. -Unknown",
  "Ketika kamu merasa kehilangan arah, ingatlah bahwa impianmu akan selalu membimbingmu ke jalan yang benar. -Unknown",
  "Jangan pernah mengabaikan orang yang mencintaimu, karena mereka adalah harta terbesarmu di dunia ini. -Unknown",
  "Kamu tidak akan pernah tahu seberapa kuat kamu sampai kamu mencoba. -Unknown",
  "Jangan pernah menyerah pada mimpi-mimpimu, karena mereka adalah potensimu yang paling besar. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk membuat perubahan positif dalam hidupmu. -Unknown",
  "Ketika kamu merasa terjebak dalam kegelapan, jangan lupa bahwa ada cahaya di ujung terowongan. -Unknown",
  "Jangan pernah mengabaikan orang yang kurang beruntung dari dirimu, karena itu adalah tanda kebesaran hati. -Unknown",
  "Kamu memiliki kekuatan untuk merubah dunia. Mulailah dari dirimu sendiri. -Unknown",
  "Jangan biarkan kegagalanmu mengalahkanmu. Ingatlah bahwa kesuksesan adalah tentang mencoba lagi dan lagi. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mencapai apa yang kamu inginkan. Kamu bisa melakukan apa saja yang kamu impikan. -Unknown",
  "Ketika kamu mengalami kesulitan, jangan lupa bahwa itu hanyalah ujian untuk membuatmu lebih kuat. -Unknown",
  "Jangan biarkan kesulitanmu menghentikanmu dari mencapai impianmu. Kesulitan hanyalah kesempatan untuk tumbuh dan berkembang. -Unknown",
  "Jangan pernah mengabaikan orang yang membutuhkan bantuanmu. Kamu mungkin satu-satunya harapan mereka. -Unknown",
  "Kamu bisa mencapai apa saja yang kamu inginkan jika kamu memiliki tekad dan ketekunan yang kuat. -Unknown",
  "Hidup adalah tentang memberikan yang terbaik dari dirimu dan menerima yang terbaik dari orang lain. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk menciptakan perubahan positif dalam hidupmu dan hidup orang lain. -Unknown",
  "Ketika kamu mengalami kegagalan, jangan menyerah. Ingatlah bahwa kegagalan adalah kesempatan untuk belajar dan tumbuh. -Unknown",
  "Jangan pernah mengabaikan kesempatan untuk belajar dan berkembang. Setiap pengalaman memiliki pelajaran yang berharga untuk dipetik. -Unknown",
  "Ketika kamu merasa terjebak dalam situasi yang sulit, jangan lupa bahwa kamu memiliki kekuatan untuk mengubahnya. -Unknown",
  "Jangan biarkan rasa takut menghalangi kamu dari mencapai impianmu. Kesuksesan datang kepada mereka yang berani mengambil risiko. -Unknown",
  "Hidup adalah tentang mengejar impianmu dan menjadikannya kenyataan. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mencapai tujuanmu. Kamu bisa melakukan apa saja yang kamu impikan. -Unknown",
  "Ketika kamu merasa kehilangan arah, jangan lupa bahwa impianmu akan selalu membimbingmu ke jalan yang benar. -Unknown",
  "Jangan biarkan kesulitanmu mengalahkanmu. Ingatlah bahwa kamu memiliki kekuatan untuk mengatasinya. -Unknown",
  "Ketika kamu merasa sendiri, jangan lupa bahwa kamu memiliki orang-orang yang mencintaimu dan selalu mendukungmu. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk membangun kepercayaan dirimu. Kamu lebih kuat dari yang kamu pikirkan. -Unknown",
  "Ketika kamu merasa lelah dan lelah, jangan menyerah. Ingatlah bahwa kamu memiliki kekuatan untuk terus maju. -Unknown",
  "Hidup adalah tentang mencapai impianmu dan membawa kebahagiaan ke dalam hidup orang lain. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mempengaruhi dunia di sekitarmu. Kamu bisa membuat perbedaan yang besar. -Unknown",
  "Ketika kamu mengalami kegagalan, jangan meratapi kegagalanmu. Gunakan kegagalanmu sebagai kesempatan untuk belajar dan tumbuh. -Unknown",
  "Jangan pernah menyerah pada impianmu. Ingatlah bahwa kamu memiliki kekuatan untuk membuatnya menjadi kenyataan. -Unknown",
  "Ketika kamu merasa kehilangan arah, jangan lupa untuk berhenti sejenak dan mencari arahmu kembali. -Unknown",
  "Jangan biarkan dirimu terjebak dalam masa lalu. Ingatlah bahwa setiap hari adalah kesempatan baru untuk memulai lagi. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mengubah hidupmu dan hidup orang lain. -Unknown",
  "Ketika kamu merasa putus asa, jangan lupa bahwa ada harapan di setiap situasi. -Unknown",
  "Jangan biarkan rasa takut menghentikanmu dari mencapai impianmu. Kamu lebih kuat dari rasa takutmu. -Unknown",
  "Ketika kamu merasa tidak dihargai, jangan lupa bahwa kamu berharga dan penting bagi dunia ini. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mencapai kesuksesan. Kamu bisa melakukan apa saja yang kamu impikan. -Unknown",
  "Ketika kamu menghadapi rintangan, jangan menyerah. Ingatlah bahwa kamu memiliki kekuatan untuk mengatasinya. -Unknown",
  "Jangan biarkan masa lalu menghentikanmu dari mencapai masa depan yang cerah. -Unknown",
  "Hidup adalah tentang menemukan kebahagiaan dalam hal-hal kecil dan membangunnya menjadi sesuatu yang besar. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk memaafkan dan melupakan masa lalu. -Unknown",
  "Ketika kamu merasa kesepian, jangan lupa bahwa kamu selalu memiliki dirimu sendiri. -Unknown",
  "Jangan biarkan rasa takut menghalangi kamu dari mencapai tujuanmu. Kamu bisa melakukan apa saja yang kamu impikan. -Unknown",
  "Ketika kamu menghadapi kesulitan, jangan menyerah. Ingatlah bahwa kamu memiliki kekuatan untuk melewatinya. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai impianmu. Kegagalan hanyalah bagian dari proses. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk menciptakan perubahan positif dalam dunia ini. -Unknown",
  "Ketika kamu merasa lelah dan lelah, jangan menyerah. Ingatlah bahwa kamu memiliki kekuatan untuk terus maju. -Unknown",
  "Jangan biarkan kesulitan menghalangi kamu dari mencapai impianmu. Kamu bisa mengatasinya. -Unknown",
  "Ketika kamu merasa tidak dihargai, jangan lupa bahwa ada orang yang peduli dan menghargai kamu. -Unknown",
  "Jangan biarkan dirimu terjebak dalam masa lalu. Masa depanmu yang cerah sedang menunggumu. -Unknown",
  "Hidup adalah tentang mengejar impianmu dan membangun masa depan yang cerah. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mencapai kesuksesan dalam hidup. Kamu lebih kuat dari yang kamu pikirkan. -Unknown",
  "Ketika kamu merasa tidak mampu, jangan menyerah. Ingatlah bahwa kamu memiliki kekuatan untuk mencapai segala sesuatu yang kamu impikan. -Unknown",
  "Jangan biarkan rasa takut menghentikanmu darimengambil risiko dan mencapai potensimu penuh. -Unknown",
  "Ketika kamu merasa sendirian, jangan lupa bahwa ada orang yang peduli dan ingin mendukungmu. -Unknown",
  "Jangan biarkan kegagalan menghalangi kamu dari mencapai impianmu. Kegagalan hanyalah pembelajaran untuk kesuksesanmu yang akan datang. -Unknown",
  "Hidup adalah tentang menemukan kedamaian dalam dirimu sendiri dan membagikannya dengan dunia di sekitarmu. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk membuat perbedaan dalam hidup orang lain. Kamu bisa menjadi seseorang yang luar biasa. -Unknown",
  "Ketika kamu merasa kehilangan arah, jangan lupa bahwa kamu selalu memiliki kekuatan untuk menemukan jalanmu kembali. -Unknown",
  "Jangan biarkan rasa tidak aman menghalangi kamu dari mencapai impianmu. Kamu bisa mengatasi ketakutanmu. -Unknown",
  "Ketika kamu merasa putus asa, jangan lupa bahwa kamu selalu memiliki kekuatan untuk bangkit kembali. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai tujuanmu. Ingatlah bahwa setiap kegagalan membawamu lebih dekat ke arah kesuksesanmu. -Unknown",
  "Hidup adalah tentang menemukan arti sejati dari kebahagiaan dan membawanya ke dalam hidupmu. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mengatasi kesulitan dan mencapai tujuanmu. Kamu bisa melakukan segalanya. -Unknown",
  "Ketika kamu merasa putus asa, jangan lupa bahwa setiap hari adalah kesempatan baru untuk memulai lagi. -Unknown",
  "Jangan biarkan kesulitan menghentikanmu dari mencapai impianmu. Kamu bisa melewatinya dengan kekuatanmu sendiri. -Unknown",
  "Ketika kamu merasa tidak dihargai, jangan lupa bahwa kamu memiliki kekuatan untuk merubah hidupmu dan hidup orang lain. -Unknown",
  "Jangan biarkan masa lalu menghantui dirimu. Masa depan yang cerah sedang menunggumu. -Unknown",
  "Hidup adalah tentang menemukan kebahagiaan dalam hal-hal kecil dan membangunnya menjadi sesuatu yang besar. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mencapai kesuksesan dalam hidup. Kamu lebih kuat dari yang kamu pikirkan. -Unknown",
  "Ketika kamu merasa tidak mampu, jangan menyerah. Ingatlah bahwa kamu memiliki kekuatan untuk mencapai impianmu. -Unknown",
  "Jangan biarkan rasa takut menghalangi kamu dari mencapai potensimu penuh. Kamu bisa menjadi seseorang yang luar biasa. -Unknown",
  "Ketika kamu merasa sendirian, jangan lupa bahwa ada orang-orang di sekitarmu yang mencintaimu dan ingin mendukungmu. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencoba lagi. Setiap kali kamu mencoba, kamu belajar dan tumbuh lebih kuat. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mencapai apa yang kamu inginkan dalam hidup. Kamu bisa melakukannya jika kamu percaya pada dirimu sendiri. -Unknown",
  "Ketika kamu merasa lelah dan lelah, jangan lupa bahwa setiap hari adalah kesempatan baru untuk memulai lagi. -Unknown",
  "Jangan biarkan ketakutan menghalangi kamu dari mencapai tujuanmu. Kamu bisa melakukannya jika kamu berani mencoba. -Unknown",
  "Ketika kamu merasa tidak terlalu yakin tentang dirimu sendiri, jangan lupa bahwa kamu adalah orang yang berharga dan penting. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai impianmu. Kamu bisa mencapainya jika kamu bertekad dan gigih. -Unknown",
  "Hidup adalah tentang menemukan keindahan dalam keadaan yang kurang sempurna dan merayakannya. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mengatasi rintangan dalam hidupmu. Kamu lebih kuat dari yang kamu pikirkan. -Unknown",
  "Ketika kamu merasa sendirian dan kesepian, jangan lupa bahwa ada orang di sekitarmu yang mencintaimu dan peduli padamu. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencoba lagi. Setiap kali kamu mencoba, kamu mendekatkan dirimu pada kesuksesan. -Unknown",
  "Ketika kamu merasa tidak mampu mengatasi masalah, jangan menyerah. Ingatlah bahwa kamu memiliki kekuatan untuk mengatasinya. -Unknown",
  "Jangan biarkan rasa takut menghentikanmu dari mencapai impianmu. Kamu bisa mencapainya jika kamu berani keluar dari zona nyamanmu. -Unknown",
  "Ketika kamu merasa terlalu lelah untuk melanjutkan, jangan lupa bahwa kamu bisa beristirahat sejenak dan melanjutkan nanti. -Unknown",
  "Jangan biarkan ketidakpastian menghalangi kamu dari mencapai tujuanmu. Kamu bisa melakukannya jika kamu percaya pada dirimu sendiri. -Unknown",
  "Jangan pernah meremehkan kekuatanmu untuk mengubah hidupmu dan hidup orang lain. Kamu bisa melakukan perubahan yang besar. -Unknown",
  "Ketika kamu merasa kehilangan arah, jangan lupa bahwa kamu selalu bisa mencari jalanmu kembali. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai tujuanmu. Kamu bisa mencapainya jika kamu tidak menyerah. -Unknown",
  "Ketika kamu merasa tidak dihargai, jangan lupa bahwa ada orang yang peduli dan menghargaimu. Teruslah melakukan yang terbaik dan kamu akan diberikan penghargaan yang layak. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencoba lagi. Setiap kegagalan adalah kesempatan untuk belajar dan tumbuh. -Unknown",
  "Ketika kamu merasa takut untuk mencoba hal baru, jangan lupa bahwa setiap kali kamu keluar dari zona nyamanmu, kamu tumbuh dan berkembang. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai tujuanmu. Kamu bisa mencapainya jika kamu tetap berfokus pada tujuanmu. -Unknown",
  "Ketika kamu merasa sendirian dan kesepian, jangan lupa bahwa ada orang di luar sana yang mencintaimu dan siap membantumu. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari bermimpi besar. Kamu bisa mencapainya jika kamu tidak pernah berhenti bermimpi dan berusaha. -Unknown",
  "Ketika kamu merasa lelah dan lelah, jangan lupa bahwa setiap tantangan yang kamu hadapi membuatmu lebih kuat dan lebih tahan terhadap masalah di masa depan. -Unknown",
  "Jangan biarkan ketidakpastian menghalangi kamu dari mencapai tujuanmu. Setiap langkah kecil membawamu lebih dekat pada tujuanmu. -Unknown",
  "Ketika kamu merasa tidak terlalu yakin tentang dirimu sendiri, jangan lupa bahwa kamu unik dan istimewa dengan caramu sendiri. -Unknown",
  "Jangan biarkan ketakutan menghalangi kamu dari mengambil tindakan. Ingatlah bahwa setiap kali kamu mengambil tindakan, kamu membuat kemajuan menuju tujuanmu. -Unknown",
  "Ketika kamu merasa tidak dihargai, jangan lupa bahwa nilai kamu tidak tergantung pada pendapat orang lain. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai impianmu. Kamu bisa mencapainya jika kamu berani mencoba lagi dan lagi. -Unknown",
  "Ketika kamu merasa kehilangan arah, jangan lupa bahwa setiap kali kamu merenung dan merefleksikan diri, kamu menemukan jalanmu kembali. -Unknown",
  "Jangan biarkan ketidakpastian menghentikanmu dari mencapai tujuanmu. Kamu bisa melakukannya jika kamu tetap fokus dan percaya pada dirimu sendiri. -Unknown",
  "Ketika kamu merasa kesulitan untuk mengatasi masalah, jangan lupa bahwa setiap masalah adalah kesempatan untuk belajar dan tumbuh. -Unknown",
  "Jangan biarkan ketakutan menghentikanmu dari mencapai tujuanmu. Kamu bisa mencapainya jika kamu berani mengambil risiko dan mengambil langkah ke depan. -Unknown",
  "Ketika kamu merasa tidak terlalu yakin tentang dirimu sendiri, jangan lupa bahwa kamu memiliki kekuatan yang luar biasa di dalam dirimu. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai tujuanmu. Kamu bisa mencapainnya jika kamu tetap gigih dan bertekad. -Unknown",
  "Ketika kamu merasa kesulitan untuk menemukan motivasi, jangan lupa bahwa setiap langkah kecil membawamu lebih dekat pada tujuanmu. -Unknown",
  "Jangan biarkan ketakutan menghalangi kamu dari meraih sukses. Kamu bisa melakukannya jika kamu memutuskan untuk berani dan mencoba. -Unknown",
  "Ketika kamu merasa kehilangan arah, jangan lupa bahwa setiap kali kamu mencari bantuan dan mendengarkan nasihat dari orang lain, kamu bisa menemukan jalanmu kembali. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari bermimpi besar. Kamu bisa mencapainya jika kamu tetap yakin pada dirimu sendiri dan terus berusaha. -Unknown",
  "Ketika kamu merasa lelah dan lelah, jangan lupa bahwa setiap kali kamu istirahat dan merawat dirimu sendiri, kamu memperkuat dirimu sendiri untuk menghadapi masa depan. -Unknown",
  "Jangan biarkan ketidakpastian menghentikanmu dari mencapai impianmu. Kamu bisa mencapainya jika kamu memutuskan untuk bertindak dan memperjuangkan impianmu. -Unknown",
  "Ketika kamu merasa takut untuk mencoba hal baru, jangan lupa bahwa setiap kali kamu mencoba sesuatu yang baru, kamu belajar dan berkembang. -Unknown",
  "Jangan biarkan ketakutan menghentikanmu dari mencapai tujuanmu. Kamu bisa melakukannya jika kamu tetap gigih dan berusaha. -Unknown",
  "Ketika kamu merasa tidak dihargai, jangan lupa bahwa kamu memiliki nilai yang tak ternilai di dalam dirimu. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai tujuanmu. Kamu bisa mencapainya jika kamu memutuskan untuk berani mencoba lagi dan lagi. -Unknown",
  "Ketika kamu merasa kehilangan arah, jangan lupa bahwa setiap kali kamu mencari petunjuk dan membuka pikiranmu, kamu bisa menemukan jalanmu kembali. -Unknown",
  "Jangan biarkan ketidakpastian menghalangi kamu dari mencapai tujuanmu. Kamu bisa mencapainya jika kamu tetap fokus pada tujuanmu dan terus maju. -Unknown",
  "Ketika kamu merasa kesulitan untuk mengatasi masalah, jangan lupa bahwa setiap kali kamu mencari solusi dan berusaha menyelesaikan masalah, kamu belajar dan tumbuh. -Unknown",
  "Jangan biarkan ketakutan menghentikanmu dari mencapai tujuanmu. Kamu bisa mencapainya jika kamu berani mengambil risiko dan mencoba yang terbaik. -Unknown",
  "Ketika kamu merasa tidak terlalu yakin tentang dirimu sendiri, jangan lupa bahwa kamu memiliki potensi yang luar biasa dan bisa meraih kesuksesan jika kamu tetap percaya pada dirimu sendiri. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari bermimpi besar. Kamu bisa mencapainya jika kamu tetap gigih dan berusaha terus-menerus. -Unknown",
  "Ketika kamu merasa kurang termotivasi, jangan lupa bahwa setiap kali kamu mencari sumber inspirasi dan membangkitkan semangatmu, kamu bisa mendapatkan motivasi yang kamu butuhkan. -Unknown",
  "Jangan biarkan ketidakpastian menghalangi kamu dari mencapai impianmu. Kamu bisa mencapainya jika kamu memiliki keberanian dan tekad yang kuat. -Unknown",
  "Ketika kamu merasa terjebak dalam rutinitas yang membosankan, jangan lupa bahwa setiap kali kamu mencoba hal baru, kamu bisa menghidupkan kembali semangatmu. -Unknown",
  "Jangan biarkan ketakutan menghentikanmu dari mencapai tujuanmu. Kamu bisa melakukannya jika kamu tetap positif dan berfokus pada tujuanmu. -Unknown",
  "Ketika kamu merasa kecewa karena kegagalan, jangan lupa bahwa setiap kali kamu mencoba lagi dan belajar dari kesalahanmu, kamu semakin dekat dengan kesuksesanmu. -Unknown",
  "Jangan biarkan ketakutan menghalangi kamu dari mencapai impianmu. Kamu bisa mencapainya jika kamu memiliki tekad dan berusaha sekuat tenaga. -Unknown",
  "Ketika kamu merasa terpuruk, jangan lupa bahwa setiap kali kamu berbicara dengan seseorang yang peduli dan mendukungmu, kamu bisa menemukan harapan dan kekuatan untuk bangkit kembali. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai tujuanmu. Kamu bisa melakukannya jika kamu tetap percaya pada dirimu sendiri dan terus berusaha. -Unknown",
  "Ketika kamu merasa tidak yakin dengan dirimu sendiri, jangan lupa bahwa setiap kali kamu menyelesaikan tugas atau tantangan yang sulit, kamu memperkuat kepercayaan dirimu sendiri. -Unknown",
  "Jangan biarkan ketakutan menghentikanmu dari mencapai tujuanmu. Kamu bisa melakukannya jika kamu berani mengambil risiko dan berusaha sebaik mungkin. -Unknown",
  "Ketika kamu merasa putus asa, jangan lupa bahwa setiap kali kamu mencari solusi dan mencoba hal-hal baru, kamu bisa menemukan jalan keluar dari masalahmu. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari bermimpi besar. Kamu bisa mencapainya jika kamu memiliki tekad yang kuat dan terus berusaha. -Unknown",
  "Ketika kamu merasa kurang termotivasi, jangan lupa bahwa setiap kali kamu mengingat alasan mengapa kamu memulai perjalananmu, kamu bisa mendapatkan kembali semangatmu. -Unknown",
  "Jangan biarkan ketidakpastian menghalangi kamu dari mencapai tujuanmu. Kamu bisa melakukannya jika kamu tetap fokus dan tidak pernah menyerah. -Unknown",
  "Ketika kamu merasa tertekan, jangan lupa bahwa setiap kali kamu berbicara dengan seseorang yang peduli, kamu bisa meredakan bebanmu dan menemukan cara untukmengatasinya. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai tujuanmu. Kamu bisa melakukannya jika kamu memiliki tekad yang kuat dan belajar dari kesalahanmu. -Unknown",
  "Ketika kamu merasa kehilangan arah, jangan lupa bahwa setiap kali kamu merencanakan langkah-langkah kecil untuk mencapai tujuanmu, kamu bisa membangun kembali visimu. -Unknown",
  "Jangan biarkan ketakutan menghentikanmu dari mencapai impianmu. Kamu bisa melakukannya jika kamu memiliki keberanian untuk mengambil risiko dan berusaha sekuat tenaga. -Unknown",
  "Ketika kamu merasa lelah dan kehabisan semangat, jangan lupa bahwa setiap kali kamu beristirahat dan mengisi kembali energimu, kamu bisa kembali bergerak maju. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari bermimpi besar. Kamu bisa mencapainya jika kamu memiliki tekad yang kuat dan terus belajar dan berkembang. -Unknown",
  "Ketika kamu merasa kesepian atau tidak ada yang mendukungmu, jangan lupa bahwa setiap kali kamu mencari sumber inspirasi dan bergabung dengan komunitas yang sejalan dengan visimu, kamu bisa menemukan teman dan dukungan. -Unknown",
  "Jangan biarkan ketidakpastian menghentikanmu dari mencapai tujuanmu. Kamu bisa melakukannya jika kamu tetap berfokus pada tujuanmu dan tidak terganggu oleh hambatan yang muncul di sepanjang jalan. -Unknown",
  "Ketika kamu merasa sedih atau kecewa, jangan lupa bahwa setiap kali kamu mengambil waktu untuk merenung dan mencari pemahaman, kamu bisa memulihkan keseimbangan emosionalmu dan kembali bergerak maju. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari bermimpi besar. Kamu bisa mencapainya jika kamu memiliki tekad yang kuat dan terus-menerus berusaha mencapai tujuanmu. -Unknown",
  "Ketika kamu merasa tidak berdaya atau takut mengambil tindakan, jangan lupa bahwa setiap kali kamu bertindak bahkan dengan tindakan kecil, kamu membangun kepercayaan dirimu sendiri dan keberanianmu. -Unknown",
  "Jangan biarkan ketidakpastian menghentikanmu dari mencapai tujuanmu. Kamu bisa melakukannya jika kamu tetap positif dan percaya pada dirimu sendiri, bahkan ketika tantangan terasa berat. -Unknown",
  "Ketika kamu merasa tidak yakin dengan dirimu sendiri atau kemampuanmu, jangan lupa bahwa setiap kali kamu belajar atau mencari bantuan dari orang lain, kamu bisa meningkatkan kepercayaan dirimu dan kemampuanmu. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai impianmu. Kamu bisa melakukannya jika kamu memiliki tekad yang kuat dan terus-menerus mengejar tujuanmu. -Unknown",
  "Ketika kamu merasa frustasi atau terhalang, jangan lupa bahwa setiap kali kamu memeriksa kembali rencana dan strategimu, kamu bisa menemukan cara baru untuk mengatasi masalah dan mencapai tujuanmu. -Unknown",
  "Jangan biarkan ketakutan menghentikanmu dari mengejar impianmu. Kamu bisa melakukannya jika kamu memiliki keberanian untuk mengambil risiko dan berusaha sekuat tenaga. -Unknown",
  "Ketika kamu merasa putus asa atau tidak yakin lagi pada tujuanmu, jangan lupa bahwa setiap kali kamu memeriksa kembali alasan dan motivasimu, kamu bisa mengingat kembali visimu dan memulai kembali perjalananmu. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mencapai impianmu. Kamu bisa melakukannya jika kamu memiliki tekad yang kuat dan terus berusaha mencapai tujuanmu. -Unknown",
  "Ketika kamu merasa terjebak dalam rutinitas atau bosan dengan kehidupanmu, jangan lupa bahwa setiap kali kamu mencari cara baru untuk berkembang dan mengeksplorasi minatmu, kamu bisa menemukan jalan keluar dan menjadi lebih bahagia. -Unknown",
  "Jangan biarkan ketakutan menghentikanmu dari mengejar impianmu. Kamu bisa melakukannya jika kamu memiliki keberanian untuk mengambil risiko dan mengejar tujuanmu dengan tekad yang kuat. -Unknown",
  "Ketika kamu merasa tidak memiliki kendali atas kehidupanmu atau situasi yang terjadi di sekitarmu, jangan lupa bahwa setiap kali kamu fokus pada hal-hal yang bisa kamu kontrol dan berusaha untuk mempengaruhi hal tersebut, kamu bisa merasa lebih bertenaga dan memperbaiki situasimu. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari bermimpi besar. Kamu bisa mencapainya jika kamu memiliki tekad yang kuat dan terus-menerus belajar dan berkembang. -Unknown",
  "Ketika kamu merasa kesepian atau tidak memiliki dukungan dari orang-orang di sekitarmu, jangan lupa bahwa setiap kali kamu mencari sumber inspirasi dan bergabung dengan komunitas yang sejalan dengan visimu, kamu bisa menemukan teman dan dukungan. -Unknown",
  "Jangan biarkan ketidakpastian menghentikanmu dari mengejar tujuanmu. Kamu bisa melakukannya jika kamu tetap fokus dan tidak terganggu oleh rintangan yang muncul di sepanjang jalan. -Unknown",
  "Ketika kamu merasa sedih atau kecewa, jangan lupa bahwa setiap kali kamu mengambil waktu untuk merenung dan mencari pemahaman, kamu bisa memulihkan keseimbangan emosionalmu dan kembali bergerak maju. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari bermimpi besar. Kamu bisa mencapainya jika kamu memiliki tekad yang kuat dan terus-menerus mengejar tujuanmu. -Unknown",
  "Ketika kamu merasa tidak yakin dengan dirimu sendiri atau kemampuanmu, jangan lupa bahwa setiap kali kamu belajar atau mencaripengalaman baru, kamu bisa membangun kepercayaan diri dan merasa lebih siap untuk menaklukkan tantangan berikutnya. -Unknown",
  "Jangan biarkan kekhawatiran menghentikanmu dari mencoba hal baru atau mengambil risiko. Kamu bisa memperoleh keberhasilan dan belajar banyak dari pengalaman tersebut. -Unknown",
  "Ketika kamu merasa terjebak dalam masalah atau situasi yang sulit, jangan lupa bahwa setiap kali kamu mencari solusi atau meminta bantuan dari orang lain, kamu bisa menemukan cara untuk mengatasi masalah tersebut. -Unknown",
  "Jangan biarkan kesuksesanmu menghentikanmu dari terus bergerak maju. Kamu harus tetap merayakan pencapaianmu, namun jangan lupa untuk terus menetapkan tujuan baru dan berkembang lebih jauh lagi. -Unknown",
  "Ketika kamu merasa kehilangan arah atau tujuan, jangan lupa bahwa setiap kali kamu mencari petunjuk atau bimbingan dari sumber-sumber yang dapat dipercaya, kamu bisa menemukan visimu kembali dan bergerak maju dengan lebih percaya diri. -Unknown",
  "Jangan biarkan kekhawatiran menghentikanmu dari mencoba hal baru atau mengambil risiko. Kamu bisa memperoleh keberhasilan dan belajar banyak dari pengalaman tersebut jika kamu memiliki tekad yang kuat. -Unknown",
  "Ketika kamu merasa terjebak dalam pola pikir yang negatif atau kebiasaan yang merugikan, jangan lupa bahwa setiap kali kamu mencari cara baru untuk mengubah pola pikirmu atau mencari sumber motivasi yang dapat memotivasimu, kamu bisa memulai perjalananmu menuju perubahan positif. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mengejar impianmu. Kamu bisa mencapainya jika kamu terus berusaha dan tidak menyerah pada rintangan yang muncul. -Unknown",
  "Ketika kamu merasa tidak memiliki kendali atas kehidupanmu atau situasi yang terjadi di sekitarmu, jangan lupa bahwa setiap kali kamu mencari cara untuk belajar dan tumbuh dari pengalaman tersebut, kamu bisa memperoleh kontrol yang lebih besar atas hidupmu. -Unknown",
  "Jangan biarkan rasa takutmu menghalangi keberhasilanmu. Kamu bisa melakukannya jika kamu memiliki tekad yang kuat dan tidak takut untuk mengambil risiko. -Unknown",
  "Ketika kamu merasa kehilangan arah atau tujuan, jangan lupa bahwa setiap kali kamu mencari motivasi atau sumber inspirasi yang baru, kamu bisa menemukan kembali visimu dan memulai perjalananmu menuju keberhasilan. -Unknown",
  "Jangan biarkan keraguan menghentikanmu dari mengejar impianmu. Kamu bisa melakukannya jika kamu terus-menerus belajar dan berusaha untuk menjadi lebih baik. -Unknown",
  "Kita tidak akan pernah tahu rezeki datangnya dari mana. Yang perlu kita lakukan hanyalah berusaha semaksimal mungkin -Unknown",
  "Ketika kamu merasa tidak yakin dengan kemampuanmu atau keputusanmu, jangan lupa bahwa setiap kali kamu mencari dukungan atau saran dari orang yang dapat dipercaya, kamu bisamendapatkan perspektif baru dan mengambil langkah yang tepat. -Unknown",
  "Jangan biarkan kegagalanmu menghentikanmu dari mencoba lagi. Kamu bisa mencapai tujuanmu jika kamu terus berusaha dan belajar dari kesalahanmu. -Unknown",
  "Ketika kamu merasa kesepian atau kehilangan dukungan dari orang lain, jangan lupa bahwa setiap kali kamu mencari teman baru atau mencari bantuan dari keluarga atau teman dekat, kamu bisa menemukan dukungan dan kenyamanan yang kamu butuhkan. -Unknown",
  "Jangan biarkan rasa takutmu menghentikanmu dari mengambil kesempatan yang tersedia. Kamu bisa mencapai kesuksesan jika kamu memiliki tekad yang kuat dan terus-menerus mengambil risiko yang tepat. -Unknown",
  "Ketika kamu merasa tidak berdaya atau tidak mampu mengubah situasi yang sulit, jangan lupa bahwa setiap kali kamu mencari sumber motivasi atau bimbingan dari orang lain, kamu bisa menemukan kekuatan dan keterampilan yang kamu butuhkan untuk mengatasi masalah tersebut. -Unknown",
  "Jangan biarkan keraguanmu menghentikanmu dari mengejar impianmu. Kamu bisa mencapainya jika kamu memiliki tekad yang kuat dan tidak takut untuk mencoba hal baru. -Unknown",
  "Ketika kamu merasa tertekan atau stres, jangan lupa bahwa setiap kali kamu mencari cara untuk merelaksasi diri atau mencari aktivitas yang dapat membantumu melepaskan stres, kamu bisa mengembalikan keseimbangan dalam hidupmu. -Unknown",
  "Jangan biarkan kekhawatiranmu menghentikanmu dari mencoba hal baru atau memperluas wawasanmu. Kamu bisa memperoleh pengetahuan baru dan pengalaman yang berharga jika kamu memiliki tekad yang kuat. -Unknown",
  "Ketika kamu merasa kesepian atau kehilangan harapan, jangan lupa bahwa setiap kali kamu mencari sumber inspirasi atau bantuan dari orang yang dapat dipercaya, kamu bisa menemukan kembali semangatmu dan terus bergerak maju. -Unknown",
  "Jangan biarkan kegagalan menghentikanmu dari mengejar impianmu. Kamu bisa mencapainya jika kamu terus-menerus belajar dan berusaha untuk menjadi lebih baik dari sebelumnya. -Unknown",
  "Ketika kamu merasa tidak mampu mengatasi masalah atau situasi yang sulit, jangan lupa bahwa setiap kali kamu mencari sumber bantuan atau dukungan dari orang lain, kamu bisa menemukan cara untuk mengatasi masalah tersebut dan memperoleh kembali kepercayaan dirimu. -Unknown",
  "Jangan biarkan rasa takutmu menghalangi kesuksesanmu. Kamu bisa mencapai tujuanmu jika kamu memiliki tekad yang kuat dan tidak takut untuk mengambil risiko yang tepat. -Unknown",
];

// Mengambil elemen HTML yang diperlukan
const birthdateInput = document.getElementById("birthdate");
const randomizeBtn = document.getElementById("randomize-btn");
const quoteText = document.getElementById("quote-text");
const quoteAuthor = document.getElementById("quote-author");

/// Menambahkan event listener pada tombol
randomizeBtn.addEventListener("click", () => {
  const birthdate = birthdateInput.value;

  // Mengecek apakah tanggal lahir sudah diisi
  if (birthdate === "") {
    alert("Silahkan pilih tanggal lahir terlebih dahulu");
    return;
  }

  // Mengambil kata-kata mutiara secara acak dari array kata-kata mutiara
  const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];

  // Menampilkan kata-kata mutiara pada elemen HTML yang sesuai
  const quoteArr = randomQuote.split("/,/");
  quoteText.textContent = quoteArr[0];
  quoteAuthor.textContent = "";
  if (quoteArr.length > 1) {
    quoteAuthor.textContent = `- ${quoteArr.slice(1).join(", ")}`;
  }
});
